### ISSUE TITLE
SPM problem

### ISSUE THREAD

**Issue by furiosFast** [rolandleth/LTHRadioButton#12]
I'm using xcode 12.5.1 and i've this error:
`package at 'https://github.com/rolandleth/LTHRadioButton.git' @ 56ef3f3dfa5766e8b4d0c983d5e2f83a08f66daf is using Swift tools version 5.5.0 but the installed version is 5.4.0 in https://github.com/rolandleth/LTHRadioButton.git
`

**Comment by rolandleth** [comment]
Hmm, maybe I should downgrade the tools to version 5. I created a branch called `tools-5`, please try and install it from there and let me know if it works and I'll merge it, if yes.

**Comment by Patmei-IDS** [comment]
tools-5 works for me in Xcode 13.2.1

**Comment by rursache** [comment]
@rolandleth please also create a new release to include that change, otherwise it will still error without specifying the branch

**Comment by rolandleth** [comment]
@rursache [Done](https://github.com/rolandleth/LTHRadioButton/releases/tag/1.2.4) (I think)
