### ISSUE TITLE
View not showing when loaded from a storyboard

### ISSUE THREAD

**Issue by neokree** [rolandleth/LTHRadioButton#3]
Hello,

The view, loaded from a storyboard, isn't showing nothing. 
I think the problem can be the absence of the initialization method `init(frame: CGRect)`.
I have this problem with Swift 3.1 and XCode 8.3.3
I have tried to install this library with cocoapods and manually, same result.

**Comment by rolandleth** [comment]
Hey Fabio,

Can you try and reproduce the bug on the demo app? The `xib` loads properly there. I don't have much experience with Storyboards, so any help would be appreciated.

Thanks!

**Comment by neokree** [comment]
I'm editing the library to found the problem. 
I will fork your library to make the bugfix and doing a pull request once found.

**Comment by rolandleth** [comment]
Awesome, thanks!

**Comment by rolandleth** [comment]
Fixed in `1.2.0`.
