### ISSUE TITLE
Not clickable by default

### ISSUE THREAD

**Issue by neokree** [rolandleth/LTHRadioButton#4]
Hello,

Essentially a radio button in web development is always clickable. 
However, your implementation does not provide the basic click funcion, so we need to add a tap gesture on the view and manually set to select state or not selected state based on the current state of the view. 
I think this initialization should be inside the view, and have a delegate that let us know when the state changed.

Let me know what you think about it
Cheers

**Comment by rolandleth** [comment]
Hey,

That makes sense. I will think of a user-friendly way to do it.

Thanks!

**Comment by rolandleth** [comment]
@neokree Can you check the latest commit, please? Would be awesome if you could let me know how the implementation feels and if you can find any weird use cases I didn't think of.

**Comment by neokree** [comment]
Hi Roland,
I tried to use your new implementation, but I don't understand how I can enable the tap gesture. 
Actually I have tried to implement the `.onSelect` and `.onDeselect` executors, but the tap gesture is not connected and the method that add the `UITapGestureRecognizer` is private, so I cannot call it from the external of the class.

**Comment by rolandleth** [comment]
Silly me, I forgot to add the call to `addTapGesture` on the `willSet` of `didDeselect`/`didSelect`.

Will do a push soon.

**Comment by rolandleth** [comment]
@neokree Can you try now, please?

**Comment by rolandleth** [comment]
Since it worked fine for me, I will consider this as solved.
