### ISSUE TITLE
UItapGestureRecognaizer is not working

### ISSUE THREAD

**Issue by yaman1987** [rolandleth/LTHRadioButton#9]
func Customizepublicbtn()
    {
        radioButton = LTHRadioButton(diameter: 18, selectedColor: .red, deselectedColor: .blue)
        radioButton.useTapGestureRecognizer = true
        radioButton.translatesAutoresizingMaskIntoConstraints = false
        self.view.addSubview(radioButton)
        radioButton.rightAnchor.constraint(equalTo: imageView.rightAnchor, constant: 0).isActive = true
        radioButton.leftAnchor.constraint(equalTo: imageView.leftAnchor, constant: 0).isActive = true
        radioButton.topAnchor.constraint(equalTo: about.bottomAnchor, constant: 20).isActive = true
        radioButton.onSelect {
            print("I'm selected.")
        }
        
        radioButton.onDeselect {
            print("I'm deselected.")
        }
        let tap = UITapGestureRecognizer(target: self, action: #selector(tapFunction))
        radioButton.addGestureRecognizer(tap)
    }
    
    @objc func tapFunction(sender:UITapGestureRecognizer) {
        print("Selected")
        radioButton.select()
    }

**Comment by rolandleth** [comment]
Hey, thanks for opening the issue. Sadly, I don't really understand what the problem is, can you give more details, please?

**Comment by yaman1987** [comment]
Hi,
i am try to create a radio button so it is created but it is not selected after taping although i ahave created UITapGestureRecognizer and added to radio button as mentioned above.

**Comment by rolandleth** [comment]
That's because the radio button already has a tap gesture. There's a property called `useTapGestureRecognizer`; set it to `true` and it will do what you're trying to do.
